[package]
name = "efreeti/json-schema-types"
version = "1.1.0-SNAPSHOT"
description = "Typed Luau JSON Schema 2020-12 models"
authors = ["Efreeti"]
license = "Apache-2.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/efreeti/luau-json-schema-types"
exclude = ["build", "build/**", "tests", "tests/**", "scripts", "scripts/**", "docs", "docs/**", "package.json", "rokit.toml", "wally.lock"]
include = ["src/**", "default.project.json", "wally.toml", "README.md", "LICENSE", "NOTICE"]

[dependencies]
