"""Translate JSON snapshots into ordinary, statically checked Luau tables."""
from pathlib import Path
import argparse, json, re
root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("--include-landscape", action="store_true", help="Include ignored local landscape fixtures")
args = parser.parse_args()
def literal(value):
    if value is None:
        return 'nil'  # Native projection: nil fields/entries cannot preserve JSON null.
    if value is True: return 'true'
    if value is False: return 'false'
    if isinstance(value, str):
        return '"' + ''.join(
            re.sub(r'\\u([0-9a-fA-F]{4})', lambda match: r'\u{' + match[1] + '}',
                   json.dumps(char, ensure_ascii=False)[1:-1])
            for char in value
        ) + '"'
    if isinstance(value, (int, float)): return repr(value)
    if isinstance(value, list): return '{ ' + ', '.join(literal(item) for item in value) + ' }'
    return '{ ' + ', '.join('[' + literal(key) + '] = ' + literal(item) for key, item in value.items()) + ' }'
lines = ['--!strict', '-- Generated by scripts/generate-fixtures.py; do not edit.', 'local Types = require("../src")', 'local fixtures: { { name: string, schema: Types.JSONSchema } } = {']
paths = list((root / 'tests/fixtures/cases').glob('*.json'))
if args.include_landscape:
    private = root / 'tests/fixtures/landscape'
    if not private.is_dir():
        parser.error('Local landscape fixture directory is missing')
    paths.extend(private.glob('*.json'))
for path in sorted(paths):
    lines.append('    { name = ' + literal(path.relative_to(root / 'tests/fixtures').as_posix()) + ', schema = ' + literal(json.loads(path.read_text())) + ' },')
lines.extend(['}', 'return fixtures'])
(root / 'tests/FixtureData.luau').write_text('\n'.join(lines) + '\n')
